### ISSUE TITLE
Only the first occurrence of a type of emoticon gets rendered

### ISSUE THREAD

**Issue by nicky1525** [simonewebdesign/real-time-web-chat#44]
If you write :) :) only the first one gets rendered.

**Comment by simonewebdesign** [comment]
I think the regex stops at the first occurrence. We should fix it so that it will replace all the occurrences in a message.

**Comment by prayashm** [comment]
Can I work on this?

**Comment by simonewebdesign** [comment]
@prayashm Sure! Go for it :)
